import {
  ChevronDownIcon,
  EyeIcon,
  FileTextIcon,
  SparklesIcon,
} from "lucide-react";
import { useCallback, useState } from "react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";
import { useResume } from "@/stores/resume";
import { exportBaseName } from "./exportName";
import { MarkdownEditor } from "./MarkdownEditor";
import { type ResumeLayoutInfo, ResumePreview } from "./ResumePreview";
import { DEFAULT_RESUME_TEMPLATE, getResumeTemplate } from "./templates";
import { usePrintResume } from "./usePrintResume";

// 当前视觉模板（尚无切换 UI，恒为默认；将来切换时改为来自状态）。
const template = getResumeTemplate(DEFAULT_RESUME_TEMPLATE);

// 去掉 HTML 注释（如内置模板的教学注释）。它不进预览/PDF，判断有无内容与导出的 Markdown 都应与之一致。
function stripHtmlComments(md: string): string {
  return md.replace(/<!--[\s\S]*?-->/g, "");
}

// 下载 Markdown 源文件（客户端生成 Blob，不经服务器）。
// 先剥掉教学注释保证导出干净（与 PDF 一致），文件名 auwe-nb-<时间戳>，末尾只留一行 auwe.app 痕迹。
function downloadMarkdown(markdown: string) {
  const name = exportBaseName();
  const body = stripHtmlComments(markdown).trim();
  const content = `${body}\n\n<!-- Generated by auwe.app · ${name} -->\n`;
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${name}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

// 简历工作台：左编辑器 / 右预览纸双栏（小屏退化为 tab）+ 底部工具栏。
export function ResumePage() {
  const markdown = useResume((s) => s.markdown);
  const setMarkdown = useResume((s) => s.setMarkdown);
  const resetToSample = useResume((s) => s.resetToSample);
  const { print } = usePrintResume();

  const [tab, setTab] = useState<"edit" | "preview">("edit");
  const [resetOpen, setResetOpen] = useState(false);
  const [autoFit, setAutoFit] = useState(false);
  // 预览分页后回报的页数/溢出/字数/章节数（均基于渲染后的实际内容）。ResumePreview 经 onLayout 更新。
  const [layout, setLayout] = useState<ResumeLayoutInfo>({
    pageCount: 1,
    overflow: false,
    charCount: 0,
    sectionCount: 0,
  });
  const onLayout = useCallback((info: ResumeLayoutInfo) => setLayout(info), []);

  // 有无内容以"剥掉注释后"为准：只剩教学注释视同空白，展示空状态、禁用导出（避免导出只有注释的文件）。
  const hasContent = stripHtmlComments(markdown).trim().length > 0;
  // 字数/章节数取自渲染后的可见文本（见 ResumePreview.countContent），已排除注释与 Markdown 语法；
  // 内容为空时预览不渲染、layout 会滞留旧值，故显式归零。
  const charCount = hasContent ? layout.charCount : 0;
  const sectionCount = hasContent ? layout.sectionCount : 0;

  return (
    <section className="flex h-[calc(100svh-3.5rem)] flex-col overflow-hidden bg-background">
      {/* 小屏 tab 切换（lg 以上隐藏，双栏并排） */}
      <div className="flex h-11 shrink-0 border-b lg:hidden">
        {(["edit", "preview"] as const).map((t) => (
          <button
            key={t}
            type="button"
            onClick={() => setTab(t)}
            className={cn(
              "flex-1 py-2 text-ui font-medium transition-colors",
              tab === t
                ? "border-b-2 border-primary text-foreground"
                : "text-muted-foreground",
            )}
          >
            {t === "edit" ? "编辑" : "预览"}
          </button>
        ))}
      </div>

      <div className="flex min-h-0 flex-1 lg:gap-4 lg:px-6 lg:py-4">
        {/* Editor Panel：白面板，浮起（发丝边 + 极淡阴影 + 面板圆角） */}
        <div
          className={cn(
            "min-h-0 flex-col overflow-hidden bg-card lg:flex lg:w-[42%] lg:min-w-[360px] lg:flex-none lg:rounded-panel lg:border lg:shadow-panel",
            tab === "edit" ? "flex flex-1" : "hidden",
          )}
        >
          <EditorPanelHeader />
          <div className="min-h-0 flex-1">
            <MarkdownEditor value={markdown} onChange={setMarkdown} />
          </div>
        </div>

        {/* Preview Stage：面板 = 顶部工具条 + 内部滚动台面（纸在其中浮起） */}
        <div
          className={cn(
            "min-h-0 flex-col overflow-hidden bg-desk lg:flex lg:flex-1 lg:rounded-panel lg:border lg:shadow-panel",
            tab === "preview" ? "flex flex-1" : "hidden",
          )}
        >
          <PreviewStageHeader
            autoFit={autoFit}
            onToggleAutoFit={() => setAutoFit((v) => !v)}
            canAutoFit={hasContent}
            pageCount={layout.pageCount}
            overflow={layout.overflow}
          />
          <div className="scroll-subtle min-h-0 flex-1 overflow-auto px-4 py-5 lg:px-6 lg:py-6">
            {hasContent ? (
              <ResumePreview
                markdown={markdown}
                autoFit={autoFit}
                onLayout={onLayout}
              />
            ) : (
              <EmptyState onRestore={resetToSample} />
            )}
          </div>
        </div>
      </div>

      {/* Command Bar：左状态 / 中上下文 / 右操作（三栏 grid，与顶栏呼应） */}
      <div className="grid h-14 shrink-0 grid-cols-[1fr_auto_1fr] items-center gap-4 border-t bg-background/80 px-6 backdrop-blur-md">
        {/* 左：状态区 —— 字数 · 章节数 · 自动保存 */}
        <div className="flex items-center gap-3 text-ui-sm text-faint">
          <span className="tabular-nums text-muted-foreground">
            {charCount} 字
          </span>
          <span aria-hidden className="hidden h-3 w-px bg-border sm:block" />
          <span className="hidden tabular-nums sm:inline">
            {sectionCount} 节
          </span>
          <span aria-hidden className="hidden h-3 w-px bg-border sm:block" />
          <span className="hidden sm:inline">
            {hasContent ? "可导出" : "待补充内容"}
          </span>
        </div>

        {/* 中：上下文 —— 模式 · 模板 */}
        <div className="hidden items-center gap-1.5 justify-self-center text-ui-sm text-faint md:flex">
          <span>简历</span>
          <span aria-hidden className="text-border-strong">
            ·
          </span>
          <span className="text-muted-foreground">{template.label} 模板</span>
        </div>

        {/* 右：操作区 —— 重置（次级）· 导出（primary 深色） */}
        <div className="flex items-center gap-2 justify-self-end">
          <AlertDialog open={resetOpen} onOpenChange={setResetOpen}>
            <AlertDialogTrigger
              render={
                <Button variant="outline" disabled={!hasContent}>
                  重置模板
                </Button>
              }
            />
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>用内置模板覆盖当前内容？</AlertDialogTitle>
                <AlertDialogDescription>
                  当前简历会被替换成内置示例模板，此操作不可撤销。
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>取消</AlertDialogCancel>
                <AlertDialogAction
                  variant="destructive"
                  onClick={() => {
                    resetToSample();
                    setResetOpen(false);
                  }}
                >
                  覆盖
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>

          <DropdownMenu>
            <DropdownMenuTrigger
              render={
                <Button disabled={!hasContent}>
                  导出
                  <ChevronDownIcon />
                </Button>
              }
            />
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={() => downloadMarkdown(markdown)}>
                导出 Markdown
              </DropdownMenuItem>
              <DropdownMenuItem onClick={print}>导出 PDF</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
    </section>
  );
}

// Editor Panel 顶部轻量工具条：文件名 + 模式标签 + 自动保存状态。
// 纯展示：内容经 zustand persist 每次编辑即写入 localStorage，故"自动保存"为实。
function EditorPanelHeader() {
  return (
    <div className="flex h-9 shrink-0 items-center gap-2.5 border-b bg-card px-3">
      <FileTextIcon aria-hidden className="size-3.5 shrink-0 text-faint" />
      <span className="text-ui-sm font-medium text-foreground">Resume.md</span>
      <Badge className="px-1.5 py-0 text-ui-xs font-medium text-muted-foreground">
        Markdown
      </Badge>
      <span className="ml-auto flex items-center gap-1.5 text-ui-xs text-faint">
        <span aria-hidden className="size-1.5 rounded-full bg-success/80" />
        自动保存
      </span>
    </div>
  );
}

interface PreviewStageHeaderProps {
  autoFit: boolean;
  onToggleAutoFit: () => void;
  canAutoFit: boolean;
  pageCount: number;
  overflow: boolean;
}

// Preview Stage 顶部轻量工具条：预览标识 + A4 + 模板名 + 智能一页开关 + 真实页数。
// “智能一页”开启后先收紧间距、再在标准区间内微调字号尽量压进一页；右侧页数由真分页给出，所见即所得。
function PreviewStageHeader({
  autoFit,
  onToggleAutoFit,
  canAutoFit,
  pageCount,
  overflow,
}: PreviewStageHeaderProps) {
  return (
    <div className="flex h-9 shrink-0 items-center gap-2.5 border-b bg-card px-3">
      <EyeIcon aria-hidden className="size-3.5 shrink-0 text-faint" />
      <span className="text-ui-sm font-medium text-foreground">预览</span>
      <Badge className="px-1.5 py-0 text-ui-xs font-medium text-muted-foreground">
        A4
      </Badge>
      <span className="text-ui-xs text-faint">{template.label}</span>

      {/* 开了智能一页但压到最紧凑档（间距到底、字号到标准区间下限）仍超目标页数：提示精简 */}
      {autoFit && overflow && (
        <span className="text-ui-xs font-medium text-warning">
          内容较多，建议精简
        </span>
      )}

      <div className="ml-auto flex items-center gap-2 text-ui-xs text-faint">
        <button
          type="button"
          onClick={onToggleAutoFit}
          disabled={!canAutoFit}
          aria-pressed={autoFit}
          title="先收紧行距段距、再在标准区间内微调字号，尽量把内容压进一页 A4"
          className={cn(
            "flex items-center gap-1.5 rounded-md px-1.5 py-0.5 font-medium transition-colors disabled:opacity-40",
            autoFit
              ? "bg-primary/10 text-primary"
              : "text-muted-foreground hover:bg-muted hover:text-foreground",
          )}
        >
          <SparklesIcon aria-hidden className="size-3" />
          智能一页
        </button>
        <span aria-hidden className="h-3 w-px bg-border" />
        <span className="tabular-nums">{pageCount} 页</span>
      </div>
    </div>
  );
}

// 空状态（预览区无内容时）：单色线条小画 + 一句话 + 恢复模板。
// 内容为空、无数据可丢，恢复直接执行、不弹确认。
function EmptyState({ onRestore }: { onRestore: () => void }) {
  return (
    <div className="mx-auto flex h-full max-w-sm flex-col items-center justify-center gap-4 text-center text-muted-foreground">
      <svg
        width="40"
        height="40"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
      >
        <path d="M14 3v4a1 1 0 0 0 1 1h4" />
        <path d="M17 21H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7l5 5v11a2 2 0 0 1-2 2Z" />
      </svg>
      <p className="text-ui leading-relaxed">
        还没有内容。开始写，或恢复内置模板。
      </p>
      <Button variant="outline" size="sm" onClick={onRestore}>
        恢复模板
      </Button>
    </div>
  );
}
