import { EditorView, type ViewUpdate } from "@uiw/react-codemirror";
import {
  BookOpenIcon,
  CheckIcon,
  ChevronDownIcon,
  FileTextIcon,
  SparklesIcon,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";
import { useResume } from "@/stores/resume";
import { AiPanel } from "./ai/AiPanel";
import { diffText } from "./ai/diff";
import { aiDiffExtension, setAiDiff } from "./ai/diffExtension";
import { SelectionToolbar } from "./ai/SelectionToolbar";
import {
  describeScope,
  paragraphRangeAt,
  sectionRangeAt,
  type TextRange,
} from "./ai/scope";
import { useResumeAi } from "./ai/store";
import { exportBaseName } from "./exportName";
import { FormatGuideDialog } from "./FormatGuideDialog";
import { MarkdownEditor } from "./MarkdownEditor";
import { type ResumeLayoutInfo, ResumePreview } from "./ResumePreview";
import { getResumeTemplate, RESUME_TEMPLATES } from "./templates";
import { usePrintResume } from "./usePrintResume";

// 去掉 HTML 注释（如内置模板的教学注释）。它不进预览/PDF，判断有无内容与导出的 Markdown 都应与之一致。
function stripHtmlComments(md: string): string {
  return md.replace(/<!--[\s\S]*?-->/g, "");
}

// 下载 Markdown 源文件（客户端生成 Blob，不经服务器）。
// 先剥掉教学注释保证导出干净（与 PDF 一致），文件名 auwe-nb-<时间戳>，末尾只留一行 auwe.app 痕迹。
function downloadMarkdown(markdown: string) {
  const name = exportBaseName();
  const body = stripHtmlComments(markdown).trim();
  const content = `${body}\n\n<!-- Generated by auwe.app · ${name} -->\n`;
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${name}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

/** 编辑器顶部「AI 优化」入口可选的范围。 */
type AiScopeKind = "selection" | "paragraph" | "section" | "document";

// 简历工作台：左编辑器 / 右预览纸双栏（小屏退化为 tab）+ 底部工具栏。
export function ResumePage() {
  const markdown = useResume((s) => s.markdown);
  const setMarkdown = useResume((s) => s.setMarkdown);
  const resetToSample = useResume((s) => s.resetToSample);
  const templateId = useResume((s) => s.template);
  const setTemplate = useResume((s) => s.setTemplate);
  const template = getResumeTemplate(templateId);
  const { print } = usePrintResume();

  const [tab, setTab] = useState<"edit" | "preview">("edit");
  const [resetOpen, setResetOpen] = useState(false);
  const [autoFit, setAutoFit] = useState(false);
  // 预览分页后回报的页数/溢出/字数/章节数（均基于渲染后的实际内容）。ResumePreview 经 onLayout 更新。
  const [layout, setLayout] = useState<ResumeLayoutInfo>({
    pageCount: 1,
    overflow: false,
    charCount: 0,
    sectionCount: 0,
  });
  const onLayout = useCallback((info: ResumeLayoutInfo) => setLayout(info), []);

  // ————— AI 优化会话 —————
  // EditorView / 容器 DOM 提升为 state（而非 ref）：效果与回调都要跟着它们重跑。
  const [editorView, setEditorView] = useState<EditorView | null>(null);
  const [editorBody, setEditorBody] = useState<HTMLDivElement | null>(null);
  const [selection, setSelection] = useState<TextRange | null>(null);

  const panelTab = useResumeAi((s) => s.panelTab);
  const setPanelTab = useResumeAi((s) => s.setPanelTab);
  const aiStatus = useResumeAi((s) => s.status);
  const aiTarget = useResumeAi((s) => s.target);
  const diffEpoch = useResumeAi((s) => s.diffEpoch);
  // 审阅/生成期间锁住正文：Diff 的偏移与原文快照强绑定，编辑会导致漂移。
  const editorLocked = aiStatus === "streaming" || aiStatus === "reviewing";

  const onEditorUpdate = useCallback((update: ViewUpdate) => {
    if (!(update.selectionSet || update.docChanged)) return;
    const main = update.state.selection.main;
    setSelection((prev) => {
      if (main.empty) return prev === null ? prev : null;
      if (prev && prev.from === main.from && prev.to === main.to) return prev;
      return { from: main.from, to: main.to };
    });
  }, []);

  const editorExtensions = useMemo(() => [aiDiffExtension], []);

  // AI 建议进入审阅态 → 在编辑器对应位置挂 Diff 装饰；其余状态清除。
  // diffEpoch 用于撤销等场景强制重挂（状态值本身不变）。
  useEffect(() => {
    void diffEpoch;
    const view = editorView;
    if (!view) return;
    if (aiStatus === "reviewing" && aiTarget) {
      const { suggestion } = useResumeAi.getState();
      view.dispatch({
        effects: [
          setAiDiff.of({
            from: aiTarget.from,
            segments: diffText(aiTarget.text, suggestion),
          }),
        ],
        // 收拢选区：残留的选区高亮会盖在 Diff 标注上，干扰辨读。
        selection: { anchor: aiTarget.from },
        scrollIntoView: false,
      });
      view.dispatch({
        effects: EditorView.scrollIntoView(aiTarget.from, { y: "center" }),
      });
    } else {
      view.dispatch({ effects: setAiDiff.of(null) });
    }
  }, [aiStatus, aiTarget, diffEpoch, editorView]);

  // 发起一轮 AI 会话：锁定范围、切到 AI 面板；带指令则直接开始生成。
  const startAi = useCallback(
    (range: TextRange, instruction?: string | null) => {
      const doc = useResume.getState().markdown;
      const from = Math.max(0, Math.min(range.from, doc.length));
      const to = Math.max(from, Math.min(range.to, doc.length));
      const text = doc.slice(from, to);
      if (!text.trim()) return;
      useResumeAi.getState().openWith({
        from,
        to,
        text,
        scope: describeScope(doc, from, to),
      });
      // 小屏没有双栏：切到「预览」tab 让右侧面板可见。
      if (!window.matchMedia("(min-width: 1024px)").matches) {
        setTab("preview");
      }
      if (instruction) void useResumeAi.getState().start(instruction);
    },
    [],
  );

  const startAiFromScope = useCallback(
    (kind: AiScopeKind) => {
      const doc = useResume.getState().markdown;
      const view = editorView;
      if (kind === "document") {
        startAi({ from: 0, to: doc.length });
        return;
      }
      const main = view?.state.selection.main;
      if (kind === "selection") {
        if (main && !main.empty) startAi({ from: main.from, to: main.to });
        return;
      }
      const pos = main?.head ?? 0;
      const range =
        kind === "paragraph"
          ? paragraphRangeAt(doc, pos)
          : sectionRangeAt(doc, pos);
      if (range) startAi(range);
    },
    [startAi, editorView],
  );

  const onToolbarAction = useCallback(
    (instruction: string | null) => {
      const main = editorView?.state.selection.main;
      if (main && !main.empty) {
        startAi({ from: main.from, to: main.to }, instruction);
      }
    },
    [startAi, editorView],
  );

  const onReselect = useCallback(() => {
    useResumeAi.getState().clearTarget();
    if (!window.matchMedia("(min-width: 1024px)").matches) setTab("edit");
    editorView?.focus();
  }, [editorView]);

  // 有无内容以"剥掉注释后"为准：只剩教学注释视同空白，展示空状态、禁用导出（避免导出只有注释的文件）。
  const hasContent = stripHtmlComments(markdown).trim().length > 0;
  // 字数/章节数取自渲染后的可见文本（见 ResumePreview.countContent），已排除注释与 Markdown 语法；
  // 内容为空时预览不渲染、layout 会滞留旧值，故显式归零。
  const charCount = hasContent ? layout.charCount : 0;
  const sectionCount = hasContent ? layout.sectionCount : 0;

  return (
    <section className="flex h-[calc(100svh-3.5rem)] flex-col overflow-hidden bg-background">
      {/* 小屏 tab 切换（lg 以上隐藏，双栏并排） */}
      <div className="flex h-11 shrink-0 border-b lg:hidden">
        {(["edit", "preview"] as const).map((t) => (
          <button
            key={t}
            type="button"
            onClick={() => setTab(t)}
            className={cn(
              "flex-1 py-2 text-ui font-medium transition-colors",
              tab === t
                ? "border-b-2 border-primary text-foreground"
                : "text-muted-foreground",
            )}
          >
            {t === "edit" ? "编辑" : "预览"}
          </button>
        ))}
      </div>

      <div className="flex min-h-0 flex-1 lg:gap-4 lg:px-6 lg:py-4">
        {/* Editor Panel：白面板，浮起（发丝边 + 极淡阴影 + 面板圆角） */}
        <div
          className={cn(
            "min-h-0 flex-col overflow-hidden bg-card lg:flex lg:w-[42%] lg:min-w-[360px] lg:flex-none lg:rounded-panel lg:border lg:shadow-panel",
            tab === "edit" ? "flex flex-1" : "hidden",
          )}
        >
          <EditorPanelHeader
            hasSelection={selection !== null}
            aiDisabled={editorLocked}
            onStartAi={startAiFromScope}
          />
          <div ref={setEditorBody} className="relative min-h-0 flex-1">
            <MarkdownEditor
              value={markdown}
              onChange={setMarkdown}
              readOnly={editorLocked}
              extraExtensions={editorExtensions}
              onCreateEditor={setEditorView}
              onUpdate={onEditorUpdate}
            />
            <SelectionToolbar
              view={editorView}
              container={editorBody}
              selection={selection}
              disabled={editorLocked}
              onAction={onToolbarAction}
            />
          </div>
        </div>

        {/* Right Stage：预览 / AI 优化 双状态面板 = 顶部工具条 + 内容区。
            AI 面板以覆盖层盖在预览上（visibility 隐藏而非卸载，保住分页测量）。 */}
        <div
          className={cn(
            "min-h-0 flex-col overflow-hidden bg-desk lg:flex lg:flex-1 lg:rounded-panel lg:border lg:shadow-panel",
            tab === "preview" ? "flex flex-1" : "hidden",
          )}
        >
          <StageHeader
            panelTab={panelTab}
            onPanelTabChange={setPanelTab}
            aiActive={aiTarget !== null}
            autoFit={autoFit}
            onToggleAutoFit={() => setAutoFit((v) => !v)}
            canAutoFit={hasContent}
            pageCount={layout.pageCount}
            overflow={layout.overflow}
            templateLabel={template.label}
          />
          <div className="relative min-h-0 flex-1">
            <div
              className={cn(
                "scroll-subtle h-full overflow-auto px-4 py-5 lg:px-6 lg:py-6",
                panelTab === "ai" && "invisible",
              )}
            >
              {hasContent ? (
                <ResumePreview
                  markdown={markdown}
                  autoFit={autoFit}
                  template={templateId}
                  onLayout={onLayout}
                />
              ) : (
                <EmptyState onRestore={resetToSample} />
              )}
            </div>
            {panelTab === "ai" && (
              <div className="absolute inset-0 bg-card duration-150 animate-in fade-in-0">
                <AiPanel onReselect={onReselect} />
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Command Bar：左状态 / 中上下文 / 右操作（三栏 grid，与顶栏呼应） */}
      <div className="grid h-14 shrink-0 grid-cols-[1fr_auto_1fr] items-center gap-4 border-t bg-background/80 px-6 backdrop-blur-md">
        {/* 左：状态区 —— 字数 · 章节数 · 自动保存 */}
        <div className="flex items-center gap-3 text-ui-sm text-faint">
          <span className="tabular-nums text-muted-foreground">
            {charCount} 字
          </span>
          <span aria-hidden className="hidden h-3 w-px bg-border sm:block" />
          <span className="hidden tabular-nums sm:inline">
            {sectionCount} 节
          </span>
          <span aria-hidden className="hidden h-3 w-px bg-border sm:block" />
          <span className="hidden sm:inline">
            {hasContent ? "可导出" : "待补充内容"}
          </span>
        </div>

        {/* 中：上下文 —— 模式 · 模板（模板可点开切换） */}
        <div className="hidden items-center gap-1.5 justify-self-center text-ui-sm text-faint md:flex">
          <span>简历</span>
          <span aria-hidden className="text-border-strong">
            ·
          </span>
          <DropdownMenu>
            <DropdownMenuTrigger
              render={
                <button
                  type="button"
                  className="flex items-center gap-1 rounded-md px-1.5 py-0.5 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
                >
                  {template.label} 模板
                  <ChevronDownIcon aria-hidden className="size-3" />
                </button>
              }
            />
            <DropdownMenuContent align="center">
              {RESUME_TEMPLATES.map((t) => (
                <DropdownMenuItem key={t.id} onClick={() => setTemplate(t.id)}>
                  <CheckIcon
                    aria-hidden
                    className={cn(
                      "size-3.5",
                      t.id === templateId ? "" : "invisible",
                    )}
                  />
                  {t.label}
                </DropdownMenuItem>
              ))}
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        {/* 右：操作区 —— 重置（次级）· 导出（primary 深色） */}
        <div className="flex items-center gap-2 justify-self-end">
          <AlertDialog open={resetOpen} onOpenChange={setResetOpen}>
            <AlertDialogTrigger
              render={
                <Button variant="outline" disabled={!hasContent}>
                  重置模板
                </Button>
              }
            />
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>用内置模板覆盖当前内容？</AlertDialogTitle>
                <AlertDialogDescription>
                  当前简历会被替换成内置示例模板，此操作不可撤销。
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>取消</AlertDialogCancel>
                <AlertDialogAction
                  variant="destructive"
                  onClick={() => {
                    resetToSample();
                    setResetOpen(false);
                  }}
                >
                  覆盖
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>

          <DropdownMenu>
            <DropdownMenuTrigger
              render={
                <Button disabled={!hasContent}>
                  导出
                  <ChevronDownIcon />
                </Button>
              }
            />
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={() => downloadMarkdown(markdown)}>
                导出 Markdown
              </DropdownMenuItem>
              <DropdownMenuItem onClick={print}>导出 PDF</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
    </section>
  );
}

interface EditorPanelHeaderProps {
  hasSelection: boolean;
  /** AI 生成/审阅期间入口置灰（正文已锁定）。 */
  aiDisabled: boolean;
  onStartAi: (kind: AiScopeKind) => void;
}

// Editor Panel 顶部轻量工具条：文件名 + 模式标签 + AI 优化入口 + 自动保存状态。
// "自动保存"为实：内容经 zustand persist 每次编辑即写入 localStorage。
function EditorPanelHeader({
  hasSelection,
  aiDisabled,
  onStartAi,
}: EditorPanelHeaderProps) {
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <div className="flex h-9 shrink-0 items-center gap-2.5 border-b bg-card px-3">
      <FileTextIcon aria-hidden className="size-3.5 shrink-0 text-faint" />
      <span className="text-ui-sm font-medium text-foreground">Resume.md</span>
      <Badge className="px-1.5 py-0 text-ui-xs font-medium text-muted-foreground">
        Markdown
      </Badge>

      {/* 格式指南：随时可查的参考弹窗，只由这里主动打开，无任何首次引导。 */}
      <FormatGuideDialog
        trigger={
          <button
            type="button"
            className="ml-auto flex items-center gap-1 rounded-md px-1.5 py-0.5 text-ui-xs font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
          >
            <BookOpenIcon aria-hidden className="size-3" />
            格式指南
          </button>
        }
      />

      {/* 有选区 → 直接对选区发起；无选区 → 弹出范围选择。 */}
      <DropdownMenu
        open={menuOpen}
        onOpenChange={(open) => {
          if (open && hasSelection) {
            onStartAi("selection");
            return;
          }
          setMenuOpen(open);
        }}
      >
        <DropdownMenuTrigger
          render={
            <button
              type="button"
              disabled={aiDisabled}
              className="flex items-center gap-1 rounded-md px-1.5 py-0.5 text-ui-xs font-medium text-primary transition-colors hover:bg-primary/10 disabled:pointer-events-none disabled:opacity-40"
            >
              <SparklesIcon aria-hidden className="size-3" />
              AI 优化
            </button>
          }
        />
        <DropdownMenuContent align="end">
          {/* GroupLabel 必须在 Group 里（Base UI 约束，否则运行时报错） */}
          <DropdownMenuGroup>
            <DropdownMenuLabel>选择优化范围</DropdownMenuLabel>
            <DropdownMenuItem onClick={() => onStartAi("paragraph")}>
              当前段落
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => onStartAi("section")}>
              当前章节
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => onStartAi("document")}>
              整份简历
            </DropdownMenuItem>
          </DropdownMenuGroup>
        </DropdownMenuContent>
      </DropdownMenu>

      <span className="flex items-center gap-1.5 text-ui-xs text-faint">
        <span aria-hidden className="size-1.5 rounded-full bg-success/80" />
        自动保存
      </span>
    </div>
  );
}

interface StageHeaderProps {
  panelTab: "preview" | "ai";
  onPanelTabChange: (tab: "preview" | "ai") => void;
  /** 有进行中的 AI 会话（预览态下给「AI 优化」标一个小圆点）。 */
  aiActive: boolean;
  autoFit: boolean;
  onToggleAutoFit: () => void;
  canAutoFit: boolean;
  pageCount: number;
  overflow: boolean;
  templateLabel: string;
}

// 右侧面板顶部工具条：预览 / AI 优化 双状态切换 + 预览态的原有控件。
// "智能一页"开启后先收紧间距、再在标准区间内微调字号尽量压进一页；右侧页数由真分页给出，所见即所得。
function StageHeader({
  panelTab,
  onPanelTabChange,
  aiActive,
  autoFit,
  onToggleAutoFit,
  canAutoFit,
  pageCount,
  overflow,
  templateLabel,
}: StageHeaderProps) {
  return (
    <div className="flex h-9 shrink-0 items-center gap-2.5 border-b bg-card px-3">
      {/* 克制的分段切换：不是主导航，只是这个面板的两个状态 */}
      <div className="grid grid-flow-col rounded-md bg-muted p-0.5 text-ui-xs">
        {(
          [
            { value: "preview", label: "预览" },
            { value: "ai", label: "AI 优化" },
          ] as const
        ).map((o) => (
          <button
            key={o.value}
            type="button"
            aria-pressed={panelTab === o.value}
            onClick={() => onPanelTabChange(o.value)}
            className={cn(
              "flex items-center gap-1 rounded-[5px] px-2 py-0.5 transition-colors outline-none focus-visible:ring-2 focus-visible:ring-ring/50",
              panelTab === o.value
                ? "bg-card font-medium text-foreground shadow-panel"
                : "text-muted-foreground hover:text-foreground",
            )}
          >
            {o.label}
            {o.value === "ai" && aiActive && panelTab !== "ai" && (
              <span
                aria-hidden
                className="size-1.5 rounded-full bg-primary/70"
              />
            )}
          </button>
        ))}
      </div>

      {panelTab === "preview" ? (
        <>
          <Badge className="px-1.5 py-0 text-ui-xs font-medium text-muted-foreground">
            A4
          </Badge>
          <span className="text-ui-xs text-faint">{templateLabel}</span>

          {/* 开了智能一页但压到最紧凑档（间距到底、字号到标准区间下限）仍超目标页数：提示精简 */}
          {autoFit && overflow && (
            <span className="text-ui-xs font-medium text-warning">
              内容较多，建议精简
            </span>
          )}

          <div className="ml-auto flex items-center gap-2 text-ui-xs text-faint">
            <button
              type="button"
              onClick={onToggleAutoFit}
              disabled={!canAutoFit}
              aria-pressed={autoFit}
              title="先收紧行距段距、再在标准区间内微调字号，尽量把内容压进一页 A4"
              className={cn(
                "flex items-center gap-1.5 rounded-md px-1.5 py-0.5 font-medium transition-colors disabled:opacity-40",
                autoFit
                  ? "bg-primary/10 text-primary"
                  : "text-muted-foreground hover:bg-muted hover:text-foreground",
              )}
            >
              <SparklesIcon aria-hidden className="size-3" />
              智能一页
            </button>
            <span aria-hidden className="h-3 w-px bg-border" />
            <span className="tabular-nums">{pageCount} 页</span>
          </div>
        </>
      ) : (
        <span className="ml-auto text-ui-xs text-faint">
          修改在左侧编辑器中审阅后才会生效
        </span>
      )}
    </div>
  );
}

// 空状态（预览区无内容时）：单色线条小画 + 一句话 + 恢复模板。
// 内容为空、无数据可丢，恢复直接执行、不弹确认。
function EmptyState({ onRestore }: { onRestore: () => void }) {
  return (
    <div className="mx-auto flex h-full max-w-sm flex-col items-center justify-center gap-4 text-center text-muted-foreground">
      <svg
        width="40"
        height="40"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
      >
        <path d="M14 3v4a1 1 0 0 0 1 1h4" />
        <path d="M17 21H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7l5 5v11a2 2 0 0 1-2 2Z" />
      </svg>
      <p className="text-ui leading-relaxed">
        还没有内容。开始写，或恢复内置模板。
      </p>
      <Button variant="outline" size="sm" onClick={onRestore}>
        恢复模板
      </Button>
    </div>
  );
}
